"""increase users.password_text length to 255

Revision ID: 50fcd2931fbf
Revises: 7f2c3d1a9add
Create Date: 2025-10-30 11:10:32.170682

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '50fcd2931fbf'
down_revision = '7f2c3d1a9add'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advisor_course_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('advisor_user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('invited', 'requested', 'accepted', 'rejected', name='advisor_link_status_enum'), nullable=False),
    sa.Column('initiated_by', sa.Enum('professor', 'advisor', 'system', name='advisor_link_initiator_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_reason', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['advisor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'advisor_user_id', name='uq_course_advisor')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_text',
               existing_type=mysql.VARCHAR(length=128),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_text',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=128),
               existing_nullable=False)

    op.drop_table('advisor_course_links')
    # ### end Alembic commands ###
